name: Build and Test

on:
  push:
    branches:
     - '*'
     - '!qa'
     - '!prod'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Test with Jest
      run: yarn lint
    - name: Build
      run: yarn build
