name: 'S3 Deploy Action'
description: 'Builds and deploys a project to AWS S3 and invalidates a CloudFront distribution cache'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_bucket_region:
    description: 'AWS Region of the S3 Bucket'
    required: true
  aws_bucket:
    description: 'Name of the S3 Bucket'
    required: true
  aws_distribution_id:
    description: 'CloudFront Distribution ID'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Build Source
      run: yarn build
      shell: bash

    - name: Debug variables
      run: |
        echo "DEV_BUCKET_REGION: ${{ inputs.aws_bucket_region }}"
        echo "DEV_BUCKET: ${{ inputs.aws_bucket }}"
        echo "DISTRIBUTION:${{ inputs.aws_distribution_id }}"
      shell: bash
      
    - name: Deploy to S3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
        aws s3 cp \
          --recursive \
          --region ${{ inputs.aws_bucket_region }} \
          dist s3://${{ inputs.aws_bucket }}

    - name: Invalidate the cache
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
           aws cloudfront create-invalidation --distribution-id ${{ inputs.aws_distribution_id }} --paths "/*"        
